[package]
name = "assemblicate"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
r2pipe = "*"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
